### ISSUE TITLE
Spoiled classification

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#141]
@mdoering, @gdower 

Have a look on this example of spoiled hierarchy:

order - suborder - infraorder - **superfamily** - **family** - genus - **superfamily** - **family** - subfamily -

![image](https://user-images.githubusercontent.com/28574252/124019188-5778bf00-d9ae-11eb-89b4-ec57c145eb5e.png)

https://www.catalogueoflife.org/?taxonKey=7NH5L

What may cause it and what to do?

**Comment by yroskov** [comment]
The problem might be in the export of WoRMS Brachyura (@bart-v) - "broken hierarchy":

![image](https://user-images.githubusercontent.com/28574252/124025617-4a5fce00-d9b6-11eb-918d-c0aaacc4a7aa.png)

**Comment by yroskov** [comment]
@mdoering, it might be a problem of the rank **Section** interpretation by the checklistbank: in Zoology Section stays between Order and Superfamily/Family, whereas in Botany Section stays between Genus & Species.

**Comment by gdower** [comment]
We tried setting the sector nomenclature to zoological and synced, which did not resolve the issue.

**Comment by yroskov** [comment]
Another example of "broken hierarchy" Genus is a child of Genus (WoRMS Ostracoda):

![image](https://user-images.githubusercontent.com/28574252/124030052-6ade5700-d9bb-11eb-9264-174c29a07391.png)

https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=f5e89bb7-9a5b-4926-92c1-d3638a78a97f--incertae-sedis--SUBGENUS

**Comment by mdoering** [comment]
You might want to first check the WoRMS data in ChecklistBank and its verbatim values

**Comment by mdoering** [comment]
Also note that the flat field `section` in ColDP is clearly defined as the botanical version only and should not be used for zoological records unless you really mean section in the botanical sense below subgenus: https://github.com/CatalogueOfLife/coldp/blob/master/README.md#section

> The (botanical) section the taxon is classified in. Considered a botanical rank below subgenus, not a zoological above family. If parentID is given this field is ignored.

**Comment by mdoering** [comment]
Looking at the verbatim record for section _Eubrachyura_ I see `parent id invalid` flagged as a serious error:
https://data.catalogueoflife.org/dataset/1108/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A106679

All invalid ID issues have the potential to seriously disrupt the tree. They should never exist in any well curated dataset and should have highest priority to be resolved.

**Comment by mdoering** [comment]
The infraorder [Brachyura](http://www.marinespecies.org/aphia.php?p=taxdetails&id=106673) with ID 106673 does not seem to be included in the WoRMS export: https://data.catalogueoflife.org/dataset/1108/verbatim?q=106673 and https://data.catalogueoflife.org/dataset/1108/verbatim?q=Brachyura&type=col%3AName

@bart-v any idea why that is?

**Comment by mdoering** [comment]
The Ostracoda example above shows 2 records, the problematic one being provisional:
https://data.catalogueoflife.org/dataset/1175/names?q=Briartina

The provisional genus record has `subgenus= Briartina` given which makes no sense for a genus. This might have to do with the problem: https://data.catalogueoflife.org/dataset/1175/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A771949

From the ID and link it seems this record should rather be the subgenus `Leperditia (Briartina) Kegel, 1933`: http://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=771949

But the [verbatim name record given in ColDP](https://data.catalogueoflife.org/dataset/1175/verbatim?type=col%3AName&col:ID=urn%3Alsid%3Amarinespecies.org%3Ataxname%3A769164&termOp=OR) declares this clearly as `rank=genus` and `scientificName=Briartina`

**Comment by mdoering** [comment]
I am surprised these genus under genus taxa are not flagged with an issue `CLASSIFICATION_RANK_ORDER_INVALID`. I will file a backend issue to make sure this happens.

**Comment by mdoering** [comment]
over 1300 bare names are also rather suspicous: https://data.catalogueoflife.org/dataset/1175/names?status=bare%20name

**Comment by gdower** [comment]
Most of the time people are including both the parent-child and flat classification because having the flattened classification makes the Taxon table more user-friendly. Would renaming the flat Taxon columns to species_name, section_name, ..., kingdom_name, etc. make them unrecognizable enough by the importer that it won't interpret them into the classification? That would be a pretty simple fix, and would let them keep the columns for usability purposes.

**Comment by mdoering** [comment]
You can add whatever other colums you like and they will just be ignored, so yes that works.
BUT the invalid parent id is the main problem, not the flat classification. Without the flat classification the section Eubrachyura would be a root taxon without any parent classification at all.

**Comment by bart-v** [comment]
* Brachyura ID 106673 is indeed not included, this happens only for the root taxon of each GSD. A bug, indeed. Looks like a small issue.
* Leperditia (Briartina) Kegel, 1933 is/was indeed problematic, the records is now fixed.
* There will always be problems like this, since Aphia does allow unaccepted parents

**Comment by mdoering** [comment]
there was indeed a bug in the flagging of badly nested ranks. Fixed in master branch and gonna be deployed tomorrow.

**Comment by mdoering** [comment]
I have fixed the issue flagging, deployed to prod and reimported [Ostracoda](https://data.catalogueoflife.org/dataset/1175/issues) and [Brachyura](https://data.catalogueoflife.org/dataset/1108/issues). Ostracoda has quite a few serious issues and 124 taxa with problematic rank ordering: https://data.catalogueoflife.org/dataset/1175/names?issue=classification%20rank%20order%20invalid

**Comment by mdoering** [comment]
It seems the Ostracoda dataset has changed since the last time. @thomasstjerne has added a new UI to show the names diff between 2 import attempts and you can see nicely the change now: https://data.catalogueoflife.org/dataset/1175/diff?attempts=13..14

**Comment by yroskov** [comment]
With a new update of 2021-07-01, the "Section" problem is still in place: 
Brachyura, 1108

![image](https://user-images.githubusercontent.com/28574252/124158353-6bc8c480-da5f-11eb-8d91-7edc423701ce.png)

**Comment by mdoering** [comment]
the parentID is still wrong in the verbatim data

**Comment by yroskov** [comment]
What will be happened if we block "Section" rank before sync?

**Comment by mdoering** [comment]
the section will just be cut out but the rest remains. So it does not help.
A) ideally we need to fix the invalid parent ID of _Eubrachyura_ so the hierarchies are not corrupted
B) I need to figure out why _Eubrachyura_ gets placed under _Lithoscaptus_. I cant see any evidence for that in the verbatim data. I will have to replay this locally and debug whats going on. This sounds like an importer bug of some sort, but I cant say what it is. From the verbatim data I would have expected _Eubrachyura_ to be placed under suborder _Pleocyemata_ even with an invalid parentID. 

So it seems we hit 2 problem together here as the cause...

**Comment by mdoering** [comment]
I've also noticed col:species in the Taxon table is given as the epithet alone. That's not what is expected, but I dont think this is related to the section issue. Still it should be a full binomial.

**Comment by gdower** [comment]
I created a version of the 1108 dataset with the Taxon table flat columns renamed to have a _name suffix, which seems to fix the problem (unless you deployed a new patch to dev): 

https://data.dev.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=058e795b-0732-4492-800d-159322c348ee&datasetKey=2169

**Comment by gdower** [comment]
The section rank does get removed though and the sectors are registered with the top taxa which are at rank section.

**Comment by mdoering** [comment]
Interesting. The parent is probably not included as the 2 sections are the top root nodes? Would have been good to include the single parent. 

Then the problem lies in the importer trying to force wrong rank orders for zoology it seems. I should be able to reproduce this in tests and find a solution. But only after my return I am afraid. But sounds like you have a workaround for this release.
