### ISSUE TITLE
Classification conflicts inside Lepidoptera

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#224]
@dhobern, I have a looked through the report on duplicated genera in the CoL (2023-04-19):

https://www.checklistbank.org/dataset/3/duplicates?category=uninomial&codeDifferent=false&limit=980&minSize=2&mode=STRICT&offset=0&rank=genus&status=accepted

It looks like there are classification conflicts between dataproviders. At least, I have spotted following conflicts:
(Classification in the examples below is incomplete. It is here as appear in the report)

(A) There is a significant set of identical genera in families **Meessiidae** at **GLI** vs **Tineidae** at **TineidaeNHM**
Lepidoptera> Tineoidea> Tineidae
vs
Lepidoptera> Tineoidea> Meessiidae

(B) genera Brachydoxa, Dryadaula, Metasticha in **GLI vs TineidaeNHM**
Lepidoptera> Tineoidea> Dryadaulidae
Lepidoptera> Tineoidea> Tineidae
and	
Lepidoptera> Tineoidea> Psychidae
Lepidoptera> Tineoidea> Tineidae

(C) genus Cryptologa in **GLI vs Global Gracillariidae**
Lepidoptera> Gracillarioidea> Douglasiidae
Gracillariidae> Gracillariinae> Gracillariini

(D) genus Phyllocnistis in **Gelechiidae vs Global Gracillariidae**
Lepidoptera> Gelechioidea> Gelechiidae
Gracillariidae> Phyllocnistinae> Phyllocnistini

(E) There is a set of identical genera in **GLI vs Gelechiidae**:	

genus Anacampsis
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Gelechiidae> Anacampsina

genus Anarsia
Gelechioidea> Gelechiidae> Dichomeridinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Barea
Gelechioidea> Oecophoridae> Oecophorinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Borkhausenia
Gelechioidea> Oecophoridae> Oecophorinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Copidostola
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Oecophoridae> Oecophorinae

genus Dichomeris
Gelechioidea> Gelechiidae> Dichomeridinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Gelechia
Lepidoptera> Gelechioidea> Gelechiidae
Gelechiidae> Gelechiinae> Gelechiini

genus Gymnobathra
Gelechioidea> Oecophoridae> Oecophorinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Hierodoris
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Oecophoridae> Oecophorinae

genus Macrobathra
Gelechioidea> Cosmopterigidae> Cosmopteriginae
Lepidoptera> Gelechioidea> Gelechiidae

genus Nothris
Gelechioidea> Gelechiidae> Anacampsinae
Lepidoptera> Gelechioidea> Gelechiidae

genus Phthorimaea
Lepidoptera> Gelechioidea> Gelechiidae
Gelechiidae> Gelechiinae> Gnorimoschemini

genus Psoricoptera
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Gelechiidae> Gelechiinae

genus Scieropepla
Lepidoptera> Gelechioidea> Gelechiidae
Lepidoptera> Gelechioidea> Xyloryctidae

genus Symmoca
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Autostichidae> Symmocinae

genus Trachyntis
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Oecophoridae> Oecophorinae

genus Xystophora
Lepidoptera> Gelechioidea> Gelechiidae
Gelechioidea> Gelechiidae> Anomologinae

**Comment by yroskov** [comment]
It would be nice to eliminate these conflicts in AC23.

I can fix cases B, C & E through blocking appropriate genera in GLI (well, we cannot guarantee that such decisions will stay and be consistently re-applied in CLB from one update to another).

It would be nice to resolve case A (Meessiidae vs Tineidae) in the source datasets.
 
In the case D (Phyllocnistis in Gelechiidae vs Global Gracillariidae), I need your advise what is a preferred placement. I can block the genus in CLB.

**Comment by dhobern** [comment]
Thanks, Yury.

Quick comments on each.

A), B) GLI is correct here - these are no longer treated as Tineidae. I am slowly working on a cleaned version of the NHM Tineidae dataset. In the meantime, please block these genera from the NHM dataset if possible. I will address more effectively as soon as I can.

C) Accept the Global Gracillariidae for this. I will move it inside GLI to avoid the collision.

D) GLI doesn't include a genus Phyllocnistis, just a species with no current name that was described in that genus. The genus should remain in Global Gracillariidae. I'll check whether I can mark the incertae sedis nature of the Gelechiidae species better.

E) I'd just found one or two of these and will fix them up.

**Comment by dhobern** [comment]
Looking at other examples, do you have a preferred way for us to mark binomials as placeholders for incertae sedis species like the "Phyllocnistis" species. In TaxonWorks, In GLI, I mark such cases as _incertae sedis_ and TW then places square brackets around the genus name. As far as I can see, no other information on the status of these names comes through from TW to CLB.

Would square brackets around the genus be sufficient to make it work on your side? Would you like any other changes?

**Comment by dhobern** [comment]
Sorry @yroskov I don't understand some of your (E) - why does it matter that these genera appear in different places within the family Gelechiidae if the Gelechiidae dataset replaces the family in GLI?

**Comment by yroskov** [comment]
> Sorry @yroskov I don't understand some of your (E) - why does it matter that these genera appear in different places within the family Gelechiidae if the Gelechiidae dataset replaces the family in GLI?

Woops! Sorry, internal Gelechiidae duplicates should be excluded from the case E.

**Comment by yroskov** [comment]
@dhobern, I included A, B & C in the plan for May edition. Unfortunately, I cannot guarantee that blocking decisions will work with further updates.

**Comment by dhobern** [comment]
Thanks - I'll work on fixing Tineidae as soon as I can.

-- 

*Donald Hobern* / ***@***.*** / +61 420511471
Araba Bioscan Project <https://stangeia.hobern.net/araba-bioscan-project/>
/ Pterophoroidea <https://pterophoroidea.hobern.net/> / Alucitoidea
<https://alucitoidea.hobern.net/> / BOLD Australia
<https://bold-au.hobern.net/>
ORCID: 0000-0001-6492-4016 <https://orcid.org/0000-0001-6492-4016> / Blog
<https://stangeia.hobern.net/> / iNaturalist
<https://inaturalist.ala.org.au/people/dhobern> / Flickr
<https://www.flickr.com/photos/dhobern/>/ GitHub
<https://github.com/dhobern> / Mastodon ***@***.***>

**Comment by dhobern** [comment]
Actually, those cases in (E) are mostly the same as your case (D) - these are incertae sedis species with binomials that do not reflect an acceptable genus. Should I enclose the genera in these cases with square brackets or do you have a preferred way to represent such cases? TaxonWorks uses the square brackets for such examples.

**Comment by yroskov** [comment]
> Looking at other examples, do you have a preferred way for us to mark binomials as placeholders for incertae sedis species like the "Phyllocnistis" species. In TaxonWorks, In GLI, I mark such cases as _incertae sedis_ and TW then places square brackets around the genus name. As far as I can see, no other information on the status of these names comes through from TW to CLB.
> 
> Would square brackets around the genus be sufficient to make it work on your side? Would you like any other changes?

As for me, square brackets with the genus for incertae sedis species is a most natural way to present temporary placement in the checklist. It is often case in zoological GSDs with unresolved taxonomy (whereas botanical GSDs create provisional combinations "nomen inedita" (flagged as "provisionally accepted" in the CoL). 

I would like to see the same presentation in the CoL, i.e. genera in square brackets in species names and in the classification with CoL status "provisionally accepted name". Unfortunately, CLB does not allow to do this (here is a report on our experiments with bracketed genera in Systema Dipterorum https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-1291120920.

@mdoering, can we. please, come back to this and alter CLB for proper handling genera in square brackets?

**Comment by yroskov** [comment]
> Actually, those cases in (E) are mostly the same as your case (D) - these are incertae sedis species with binomials that do not reflect an acceptable genus. Should I enclose the genera in these cases with square brackets or do you have a preferred way to represent such cases? TaxonWorks uses the square brackets for such examples.

I would chose square brackets for these cases. At lest, it removes user confusion with split genera in the Tree.

**Comment by mdoering** [comment]
Basically the name is a name, not a vehicle for all kinds of extra information.

**Comment by mdoering** [comment]
> > COL strongly recommends **to flag the species taxon with provisional=true**
> 
> It is exactly what I cannot succeed in CLB.
> 
> @mdoering, are GSDs able to flag these names as "provisional=true" in their CoLDP export?

Of course they can. Either via [Taxon.provisional](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#provisional) or `NameUsage.status=provisionally accepted` depending on how they share their data.

**Comment by dhobern** [comment]
Great - I have the provisional status in my other datasets but forgot to set it for these. They should be good now. So you can reimport Gelechiidae whenever suits you.

**Comment by yroskov** [comment]
Done.  Gelechiidae synced for May edition.

**Comment by yroskov** [comment]
List of Meessiidae genera in GLI (35):
Lichenotinea	Petersen, 1957
Matratinea	Sziraki, 1990
Mea	Busck, 1906
Meneessia	Zagulajev, 1974
Montetinea	Petersen, 1957
Nannotinea	Gozmány, 1966
Novotinea	Amsel, 1939
Oenoe	Chambers, 1874
Omichlospora	Meyrick, 1928
Oxylychna	Meyrick, 1916
Pompostolella	Fletcher, 1940
Stenoptinea	Dietz, 1905
Tenaga	Clemens, 1862
Tineiforma	Amsel, 1952
Trissochyta	Meyrick, 1921
Xeringinia	Robinson & Nielsen, 1993

**Comment by yroskov** [comment]
- [x] (B) genera Brachydoxa, Dryadaula, Metasticha in GLI vs TineidaeNHM = FIXED 2023-04-26, blocked in TineidaeNHM

**Comment by yroskov** [comment]
- [ ] (C) genus Cryptologa in GLI vs Global Gracillariidae = FIXED in GLI. GLI need to be re-synced.

**Comment by yroskov** [comment]
- [ ] (D) genus Phyllocnistis in Gelechiidae vs Global Gracillariidae
>D) GLI doesn't include a genus Phyllocnistis, just a species with no current name that was described in that genus. The genus should remain in Global Gracillariidae. I'll check whether I can mark the incertae sedis nature of the Gelechiidae species better.

As present 2023-04-26 in Gelechiidae 1.1.23.115 (25 Apr 2023):
![image](https://user-images.githubusercontent.com/28574252/234703652-c61b8655-97f0-453b-ae1b-c09de54a35a8.png)

**Gelechiidae re-synced 2023-04-26**

**Comment by yroskov** [comment]
- [ ] (E) There is a set of identical genera in GLI vs Gelechiidae

**Gelechiidae re-synced 2023-04-26**

**Comment by dhobern** [comment]
Aaargh - sorry. I somehow reverted the provisional flags on the unplaced species, including _[Phyllocnistis] spilota_ - these are fixed again for next time you import.

**Comment by yroskov** [comment]
>Either via [Taxon.provisional](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#provisional) or NameUsage.status=provisionally accepted depending on how they share their data.

@mdoering, seems, "provisional" flag does not work with "unplaced genera": genus _Phyllocnistis_ (with a single species name Phyllocnistis spilota) still appear in Gelechiidae GSD as "accepted" (it happens after sync of fixed Gelechiidae ver. 1.1.23.117 (27 Apr 2023) / 2023-04-27) - see my report two blocks above.
